version: '2'
services:
  web:
    image: node:latest
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    env_file: .env
    links:
      - postgres
    ports:
      - "8000:8000"
      - "8888:8888"
    depends_on:
      - postgres
    command: bash -c "npm install -g knex && knex migrate:latest --env production && knex seed:run --env production && npm start"
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=lango
      - POSTGRES_USER=lango
