version: '2'
services:
  web:
    image: node:latest
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    env_file: .env
    links:
      - postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: bash -c "npm install -g knex && knex migrate:latest --env production && npm start"
  postgres:
    image: postgres
    expose:
      - 5432
    environment:
      - DB_NAME=lango
      - DB_USER=lango
